# =====================================================
arm:
    #ee group name
    base_link : 'world_frame'
    end_effector_name: 'gripper'

    #actuated joints in end effector
    joints : ['finger_middle_joint_1', 'finger_1_joint_1', 'finger_2_joint_1']

    #open position
    pregrasp_posture : [0.0, 0.0, 0.0]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [1.0, 1.0, 1.0]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [-0.01, 0, -0.1]

    end_effector_parent_link: 'palm'
